# -*- coding: utf-8 -*-
from odoo import models, fields, api

class SaleOrder(models.Model):
    _inherit = 'sale.order'

    provider_id = fields.Many2one('abershum.provider', string='Provider', tracking=True)

    def action_confirm(self):
        res = super(SaleOrder, self).action_confirm()
        for order in self:
            for line in order.order_line:
                if line.product_id.is_radiology:
                    self.env['orthanc.order'].create({
                        'sale_order_id': order.id,
                        'product_id': line.product_id.id,
                        # study_uuid and name generated by create method
                    })
                    # Trigger send to orthanc immediately? 
                    # Requirements say: "When a sales order is confirmed, if the sales order has a radiology order then it send the order to Orthanc server."
                    # The record is stored there. And create an emtpty method with logger with name _send_to_orthanc
                    
                    # We should probably call the method on the created record.
                    # Getting the last created record for this line is safer done by returning it from create if we did it explicitly,
                    # but since we are iterating, we can just search for what we just made or assign to a variable.
                    
        # After creating all orders, we might want to trigger the send.
        # Let's do it cleaner: identify lines, create orders, then trigger.
        
        # Re-iterating to capture the objects
        for order in self:
             radiology_lines = order.order_line.filtered(lambda l: l.product_id.is_radiology)
             for line in radiology_lines:
                 # Check if order already exists to prevent duplicates if confirm is called multiple times (though action_confirm state change usually prevents this)
                 # But good practice.
                 existing = self.env['orthanc.order'].search([
                     ('sale_order_id', '=', order.id),
                     ('product_id', '=', line.product_id.id)
                 ], limit=1)
                 
    def action_cancel(self):
        res = super(SaleOrder, self).action_cancel()
        for order in self:
            # OPTIMIZE: This could be done with a search on sale_order_id to handle all at once
            orthanc_orders = self.env['orthanc.order'].search([
                ('sale_order_id', '=', order.id),
                ('state', '!=', 'cancelled')
            ])
            for orthanc_order in orthanc_orders:
                orthanc_order.write({
                    'state': 'cancelled',
                    'cancel_reason': f"Sales Order {order.name} was cancelled."
                })
        return res
